version: '3.9'

services:
  todoapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/postgres
      DB_USER: hlm
      DB_PASS: 1qaz!QAZ

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: hlm
      POSTGRES_PASSWORD: 1qaz!QAZ
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
